services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
      
  frontend:
    build:
      context: ./react-app-example
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./test
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=true
    networks:
      - app-network
    command: java -jar /app/kopring-app.jar --debug

networks:
  app-network:
    driver: bridge