services:
  frontend:
    build:
      context: ./react-app-example
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Nginx를 3000 포트에 매핑

  backend:
    build:
      context: ./test
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Spring Boot를 8080 포트에 매핑
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=true
    networks:
      - backend-network
    command: java -jar /app/kopring-app.jar --debug

networks:
  backend-network:
    driver: bridge